project:
  type: book
  output-dir: render
  
book:
  title: "IFN Analysis 🌲"
  subtitle: "Analysing drivers of forest change in France"
  author: 
    - name: "Pascal Schneider"
  date: "`r Sys.Date()`"
  page-navigation: true
  chapters:
    - index.qmd
    - 01-dataset-description.qmd
    - 02-data-exploration.qmd
    - 03-subset-exploration.qmd
  search: true
  navbar: 
    right:
      - icon: github
        href: https://github.com/padasch/analysis_ifn
        aria-label: GitHub

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 4
    grid: 
      body-width: 1900px
      sidebar-width: 250px
      margin-width: 250px
    code-fold: show
    code-tools: true
    code-line-numbers: true

editor: visual

knitr:
  opts_chunk:
    out.width: "80%"
    fig.align: "center"
    
execute:
  freeze: auto 
  cache: false
  message: false
  warning: false
