get_vars <- function(subset) {
  
  if (subset == "nature") {
    
    out <- 
      c("nincid_1", 
        "nincid_2", 
        "incid_1", 
        "incid_2",
        "sfgeliv_1", 
        "sfgeliv_2", 
        "sfgui_1", 
        "sfgui_2", 
        "sfdorge_1", 
        "sfdorge_2", 
        "mortb_1", 
        "mortb_2",
        "dpyr", 
        "deggib", 
        "sfcoeur", 
        "sfpied", 
        "acci"
        ) 
    
  } else if (subset == "human") {
    
    out <- 
      c(
        "def5", 
        "instp5", 
        "prelev5",
        "nlisi5",
        "andain", 
        "dc", 
        "elag", 
        "gest", 
        "tplant", 
        "tetard"
      )
    
  } else if (subset == "irrelevant") {
    out <- 
      c(
        "acces", 
        "asperite", 
        "autut", 
        "bois", 
        "bplant", 
        "dcespar1", 
        "dcespar2", 
        "dist", 
        "integr", 
        "iplant", 
        "iti", 
        "pentexp", 
        "portance", 
        "portn", 
        "tform", 
        "tm2", 
        "tpespar1", 
        "tpespar2", 
        "videpeuplier", 
        "videplant",
        "entp"
      )
  } else if (subset == "tree_lvl") {
    out <- c(
      
      # Created by hand
      "visit_1",
      "visit_2",
      "revisit_state",
      "census_interval",
      "tree_state_1",
      "tree_state_2",
      "alive_but_injured_1",
      "alive_but_injured_2",
      "mode_of_death",
      "tree_state_change",
      "tree_class",
      "species_lat",
      "genus_lat",
      "family_lat",
      "order_lat",
      "age_class",
      "height_class",
      "shadow_growth",
      "c13_change_abs_yr",
      "c13_change_perc_yr",
      "dbh_1",
      "dbh_2",
      "dbh_change_abs_yr",
      "dbh_change_perc_yr",
      "ba_1",
      "ba_2",
      "ba_change_abs_yr",
      "ba_change_perc_yr",
      "avg_growth_height_meter_per_yr",
      "avg_growth_ba_per_year",
      
      # From data
      "a",
      "tree_id",
      "hrb",
      "campagne_1",
      "campagne_2",
      "visite_1",
      "visite_2",
      "c13_1",
      "c13_2",
      "mortb_1",
      "mortb_2",
      "sfdorge_1",
      "sfdorge_2",
      "sfgeliv_1",
      "sfgeliv_2",
      "sfgui_1",
      "sfgui_2",
      "veget",
      "q1",
      "q2",
      "q3",
      "age13",
      "age",
      "c0",
      "htot",
      "hdec",
      "ddec",
      "lfsd",
      "v",
      "w",
      "r",
      "ir5",
      "ir1",
      "espar",
      "datemort",
      "ori",
      "tige",
      "forme",
      "tetard",
      "cible",
      "lib",
      "simplif",
      "acci",
      "clon",
      "mes_c13",
      "decoupe",
      "sfcoeur",
      "sfpied",
      "deggib",
      "veget5",
      "qualite"
    )
    
  } else if (subset == "site_lvl") {
    
    out <- 
      c(
        # created by hand
        "land_use",
        "land_use_change",
        "cover_change",
        "human_activity",
        "human_activity_var",
        "perc_cut",
        "dominant_species",
        "dominant_tree_class",
        "gre",
        
        # widened placette
        "idp", 
        "lon_fr", 
        "lat_fr", 
        "dep", 
        "ser", 
        "dpyr", 
        "anpyr", 
        "pbuis", 
        "lat", 
        "lon", 
        "campagne_1", 
        "campagne_2", 
        "visite_1", 
        "visite_2", 
        "incid_1", 
        "incid_2", 
        "nincid_1", 
        "nincid_2", 
        "tpespar1_1", 
        "tpespar1_2", 
        "tpespar2_1", 
        "tpespar2_2", 
        "bplant_1", 
        "bplant_2", 
        "iplant_1", 
        "iplant_2", 
        "videpeuplier_1", 
        "videpeuplier_2", 
        "csa_1", 
        "csa_2", 
        "bois_1", 
        "bois_2", 
        "peupnr_1", 
        "peupnr_2", 
        "utip_1", 
        "utip_2", 
        "autut_1", 
        "autut_2", 
        "tform_1", 
        "tform_2", 
        "dc_1", 
        "dc_2", 
        "gest", 
        "elag", 
        "dist", 
        "acces", 
        "iti", 
        "asperite", 
        "pentexp", 
        "portn", 
        "portance", 
        "orniere", 
        "dcespar1", 
        "dcespar2", 
        "tplant", 
        "videplant", 
        "entp", 
        "tcat10", 
        "uta1", 
        "uta2", 
        "plisi", 
        "cslisi", 
        "elisi", 
        "andain", 
        "bord", 
        "integr", 
        "tm2", 
        "sfo", 
        "cam", 
        "prelev5", 
        "def5", 
        "instp5", 
        "nlisi5", 
        "sver", 
        
        # couvert
        "campagne",
        "idp",
        "strate",
        "espar_c",
        "tca",
        "tcl",
        "p1525",
        "p7ares",
        
        # ecologie
        "campagne",
        "idp",
        "dateeco",
        "topo",
        "obstopo",
        "expo",
        "msud",
        "masque",
        "pent2",
        "obschemin",
        "humus",
        "oln",
        "olt",
        "ofr",
        "olv",
        "oh",
        "tsol",
        "prof1",
        "prof2",
        "obsprof",
        "text1",
        "text2",
        "obspedo",
        "roche",
        "obsroc",
        "affroc",
        "cai40",
        "cailloux",
        "typcai",
        "afpla",
        "pgley",
        "pox",
        "ppseudo",
        "obshydr",
        "pcalc",
        "pcalf",
        "obsriv",
        "obsriv2",
        "typriv",
        "distriv",
        "denivriv",
        "lign2",
        "lign1",
        "herb",
        "mousse",
        "obsveget",
        "obsdate",
        
        # habitat
        "campagne",
        "idp",
        "hab",
        "qualhab",
        "obshab",
        "association",
        "alliance",
        "ordre",
        "classe",
        "cb_ifn",
        "cd_hab",
        "hic",
        "eunis"
        ) |> 
      unique()
    
  } else {
    stop("Non-valid subset input")
  }
  
  return(out)
}
